### ISSUE TITLE
Unable to create project during setup

### ISSUE THREAD

**Issue by articoder** [UCDenver-ccp/Knowtator-2.0#25]
Hi guys,
I followed the setup steps, but there is no response after I enter the project name. Also no response from the rest of the buttons in Knowtator.

The environment is:
   INFO  01:26:44  Protege Desktop
   INFO  01:26:44  Version 5.5.0, Build 
   INFO  01:26:44  Java: JVM 1.8.0_121-b13  Memory: 3817M
   INFO  01:26:44  Framework: Apache Software Foundation (1.8) 
   INFO  01:26:44  OS: macosx (10.15)
   INFO  01:26:44  Processor: x86-64

And here is the list of error messages:
   WARN  01:26:53  Don't worry about the following exception. Just forcing loading of a class needed by mxGraph
  ERROR  01:27:08  Uncaught Exception in thread 'AWT-EventQueue-0'
java.lang.NullPointerException: null
	at edu.ucdenver.ccp.knowtator.view.menu.FilePane.executeNew(FilePane.java:64) ~[na:na]
	at edu.ucdenver.ccp.knowtator.view.menu.FilePane.lambda$new$1(FilePane.java:55) ~[na:na]
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022) ~[na:1.8.0_121]
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348) ~[na:1.8.0_121]
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402) ~[na:1.8.0_121]
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259) ~[na:1.8.0_121]
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252) ~[na:1.8.0_121]
	at java.awt.Component.processMouseEvent(Component.java:6533) ~[na:1.8.0_121]
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324) ~[na:1.8.0_121]
	at java.awt.Component.processEvent(Component.java:6298) ~[na:1.8.0_121]
	at java.awt.Container.processEvent(Container.java:2236) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEventImpl(Component.java:4889) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2294) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888) ~[na:1.8.0_121]
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525) ~[na:1.8.0_121]
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466) ~[na:1.8.0_121]
	at java.awt.Container.dispatchEventImpl(Container.java:2280) ~[na:1.8.0_121]
	at java.awt.Window.dispatchEventImpl(Window.java:2746) ~[na:1.8.0_121]
	at java.awt.Component.dispatchEvent(Component.java:4711) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758) ~[na:1.8.0_121]
	at java.awt.EventQueue.access$500(EventQueue.java:97) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:709) ~[na:1.8.0_121]
	at java.awt.EventQueue$3.run(EventQueue.java:703) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90) ~[na:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:731) ~[na:1.8.0_121]
	at java.awt.EventQueue$4.run(EventQueue.java:729) ~[na:1.8.0_121]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_121]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80) ~[na:1.8.0_121]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728) ~[na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [na:1.8.0_121]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93) [na:1.8.0_121]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82) [na:1.8.0_121]

Any idea to solve this problem? Many thanks!

**Comment by articoder** [comment]
Problem solved, the latest release 2.1.6(https://github.com/UCDenver-ccp/Knowtator-2.0/releases/tag/2.1.6) works for me on Protege 5.5.0.
